(function AIVO_RADIO_AD_SHELL(){
  "use strict";
  if(window.__AIVO_RADIO_AD_SHELL_READY__) return;
  window.__AIVO_RADIO_AD_SHELL_READY__=true;

  const COPY={
    tr:{nav:"AI Radyo Reklamı",newBadge:"YENİ",selectorLabel:"Reklam Türünü Seç",video:"Reklam Videosu",radio:"Radyo Reklamı",videoTitle:"AI Reklam Videosu Oluştur",panelTitle:"Radyo Reklamlarım",panelMeta:"Yeni modül",previewTitle:"Canlı ses önizleme",previewText:"Seslendirme, müzik ve jingle seçimleri burada özetlenecek.",emptyTitle:"İlk radyo reklamın burada görünecek",emptyText:"Üretim motoru bağlandıktan sonra hazırladığın reklamları buradan dinleyip indirebileceksin."},
    en:{nav:"AI Radio Ad",newBadge:"NEW",selectorLabel:"Choose Ad Type",video:"Video Ad",radio:"Radio Ad",videoTitle:"Create AI Video Ad",panelTitle:"My Radio Ads",panelMeta:"New module",previewTitle:"Live audio preview",previewText:"Narration, music and jingle choices will be summarized here.",emptyTitle:"Your first radio ad will appear here",emptyText:"After the production engine is connected, you will be able to listen to and download your ads here."}
  };

  const state={duration:30,speed:"fast",flow:"natural",musicMode:"ai",jingleMode:"ai"};
  const JINGLE_LIMIT={15:4,30:6,45:7,60:8};
  const WORD_RATE={slow:1.55,balanced:1.9,fast:2.2};

  function lang(){let stored="";try{stored=String(localStorage.getItem("aivo_language")||localStorage.getItem("aivo_lang")||"").toLowerCase()}catch(_){}const html=String(document.documentElement.lang||"").toLowerCase();return stored==="en"||html.indexOf("en")===0?"en":"tr"}
  function t(key){return COPY[lang()][key]||COPY.tr[key]||key}
  function q(root,sel){return(root||document).querySelector(sel)}
  function qa(root,sel){return Array.from((root||document).querySelectorAll(sel))}
  function words(text){try{return String(text||"").match(/[\p{L}\p{N}]+(?:[’'\-.][\p{L}\p{N}]+)*/gu)||[]}catch(_){return String(text||"").trim().split(/\s+/).filter(Boolean)}}
  function pad(value){return String(Math.max(0,Math.round(value))).padStart(2,"0")}
  function mmss(seconds){return"00:"+pad(seconds)}

  function ensureCss(){if(document.querySelector('link[href^="/css/radio-ad.css"]'))return;const link=document.createElement("link");link.rel="stylesheet";link.href="/css/radio-ad.css?v=2";document.head.appendChild(link)}
  function icon(){return '<span class="radio-ad-nav-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><rect x="8" y="3" width="8" height="12" rx="4" stroke="currentColor" stroke-width="1.8"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3M8 21h8" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M3 7.5c-1.2 1.4-1.2 7.6 0 9M21 7.5c1.2 1.4 1.2 7.6 0 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg></span>'}

  function ensureNav(){const card=document.querySelector("#leftMenu .navCard");if(!card)return;let btn=card.querySelector('[data-route="radioad"]');if(!btn){btn=document.createElement("button");btn.type="button";btn.className="navBtn";btn.dataset.route="radioad";const adFilm=card.querySelector("[data-adfilm-open]");const lipsync=card.querySelector('[data-route="lipsync"]');if(adFilm)adFilm.insertAdjacentElement("afterend",btn);else if(lipsync)lipsync.insertAdjacentElement("afterend",btn);else card.appendChild(btn)}btn.setAttribute("aria-label",t("nav"));btn.innerHTML=icon()+'<span data-radio-ad-nav-label>'+t("nav")+'</span><span class="radio-ad-nav-badge">'+t("newBadge")+'</span>'}
  function applyVideoNaming(root){const nav=document.querySelector("[data-adfilm-nav-label]");if(nav)nav.textContent=lang()==="en"?"AI Video Ad":"AI Reklam Videosu";const scope=root||document.querySelector('[data-module-root][data-module="adfilm"]');const title=scope&&scope.querySelector("#adfilmTitle");if(title)title.textContent=t("videoTitle")}

  function selector(active){const section=document.createElement("section");section.className="radio-ad-type-switch";section.dataset.radioAdTypeSwitch="1";section.innerHTML='<span class="radio-ad-type-switch__label">'+t("selectorLabel")+'</span><div class="radio-ad-type-switch__track" role="tablist"><button type="button" data-ad-type="video" class="'+(active==="video"?"is-active":"")+'" aria-selected="'+(active==="video")+'">'+t("video")+'</button><button type="button" data-ad-type="radio" class="'+(active==="radio"?"is-active":"")+'" aria-selected="'+(active==="radio")+'">'+t("radio")+'</button></div>';section.addEventListener("click",function(event){const button=event.target.closest("[data-ad-type]");if(!button)return;const target=button.dataset.adType==="radio"?"radioad":"adfilm";if(window.StudioRouter&&typeof window.StudioRouter.setHash==="function")window.StudioRouter.setHash(target);else location.hash="#"+target});return section}
  function ensureSelector(key,root){if(!root)return;const old=root.querySelector(':scope > [data-radio-ad-type-switch="1"]');if(old)old.remove();const anchor=key==="adfilm"?root.querySelector(".adfilm-hero"):root.querySelector(".radio-ad-hero");if(!anchor)return;anchor.insertAdjacentElement("afterend",selector(key==="adfilm"?"video":"radio"));if(key==="adfilm")applyVideoNaming(root)}

  function registerPanel(){if(!window.RightPanel||window.RightPanel._has&&window.RightPanel._has("radioad"))return;window.RightPanel.register("radioad",{getHeader:function(){return{title:t("panelTitle"),meta:t("panelMeta"),searchEnabled:false,resetSearch:true}},mount:function(wrap){wrap.innerHTML='<div class="radio-ad-panel"><section class="radio-ad-panel__preview"><strong>'+t("previewTitle")+'</strong><div class="radio-ad-wave" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><p>'+t("previewText")+'</p><div class="radio-ad-panel__meta"><span>00:00</span><span data-radio-panel-duration>30 sn</span></div></section><section class="radio-ad-panel__empty"><b>'+t("emptyTitle")+'</b><span>'+t("emptyText")+'</span></section></div>'},onShow:function(_,ctx){ctx.setHeader({title:t("panelTitle"),meta:t("panelMeta"),searchEnabled:false})}})}

  function usableVoiceSeconds(){const jingle=state.jingleMode==="off"?0:JINGLE_LIMIT[state.duration];const intro=state.musicMode==="off"?0:1;return Math.max(5,state.duration-jingle-intro)}
  function wordRange(){const seconds=usableVoiceSeconds();const rate=WORD_RATE[state.speed]||WORD_RATE.fast;const max=Math.floor(seconds*rate);return{min:Math.max(5,Math.floor(max*.72)),max,seconds}}

  function updateBudget(root){const copy=q(root,"[data-radio-ad-copy]");const count=words(copy&&copy.value).length;const range=wordRange();const estimate=count/(WORD_RATE[state.speed]||2.2);const rangeEl=q(root,"[data-radio-ad-word-range]");const countEl=q(root,"[data-radio-ad-word-count]");const estimateEl=q(root,"[data-radio-ad-estimate]");const badge=q(root,"[data-radio-ad-duration-badge]");const fill=q(root,"[data-radio-ad-budget-fill]");const message=q(root,"[data-radio-ad-budget-message]");if(rangeEl)rangeEl.textContent=range.min+"–"+range.max+" kelime önerilir";if(countEl)countEl.textContent=count;if(estimateEl)estimateEl.textContent=Math.max(0,Math.ceil(estimate));if(badge)badge.textContent=state.duration+" sn";if(fill)fill.style.width=Math.min(100,Math.round(count/Math.max(1,range.max)*100))+"%";if(message){if(count>range.max)message.textContent="Bu metin seçilen konuşma alanına sığmıyor. Metni kısalt veya reklam süresini artır.";else if(count>range.max*.9)message.textContent="Sınıra yakın. Doğal duraklar için birkaç kelime kısaltmak daha güvenli.";else message.textContent="AIVO, jingle ve müzik girişini hesaba katarak kullanılabilir konuşma süresini otomatik ayarlar."}const budget=q(root,"[data-radio-ad-budget]");if(budget)budget.classList.toggle("is-over",count>range.max)}

  function updateTimeline(root){const duration=state.duration;const jingle=state.jingleMode==="off"?0:JINGLE_LIMIT[duration];const intro=state.musicMode==="off"?0:1;const voice=Math.max(0,duration-jingle-intro);const main=q(root,"[data-radio-ad-timeline-main]");if(main){main.innerHTML="";if(intro){const s=document.createElement("span");s.className="is-intro";s.style.width=(intro/duration*100)+"%";s.textContent="Müzik girişi";main.appendChild(s)}if(voice){const s=document.createElement("span");s.className="is-voice";s.style.width=(voice/duration*100)+"%";s.textContent="Seslendirme";main.appendChild(s)}if(jingle){const s=document.createElement("span");s.className="is-jingle";s.style.width=(jingle/duration*100)+"%";s.textContent="Jingle";main.appendChild(s)}}const bed=q(root,"[data-radio-ad-timeline-bed]");if(bed)bed.innerHTML=state.musicMode==="off"?'<span class="is-off">Arka plan müziği kapalı</span>':'<span>Arka plan müziği · 00:00–'+mmss(duration)+'</span>';const legend=q(root,"[data-radio-ad-timeline-legend]");if(legend)legend.innerHTML=(intro?'<span><i class="is-intro"></i>Müzik girişi: '+intro+' sn</span>':'')+'<span><i class="is-voice"></i>Seslendirme: '+voice+' sn</span>'+(jingle?'<span><i class="is-jingle"></i>Jingle: '+jingle+' sn</span>':'');const total=q(root,"[data-radio-ad-total-time]");if(total)total.textContent=mmss(duration);const jd=q(root,"[data-radio-ad-jingle-duration]");if(jd)jd.textContent=jingle+" sn";const jn=q(root,"[data-radio-ad-jingle-note]");if(jn)jn.textContent=jingle?duration+" saniyelik reklam için önerilen üst sınır.":"Jingle kapalı.";const final=q(root,"[data-radio-ad-final-summary]");if(final)final.textContent=duration+" sn · MP3 320 kbps + WAV · "+(state.musicMode==="off"?"Müziksiz":"Müzik")+(state.jingleMode==="off"?"":" + kapanış jingle’ı");const footer=q(root,"[data-radio-ad-footer-summary]");if(footer)footer.textContent=duration+" sn · Sesli · "+(state.musicMode==="ai"?"AIVO müziği":state.musicMode==="upload"?"Yüklenen müzik":"Müziksiz")+" · "+(state.jingleMode==="ai"?"AIVO sonic logo":state.jingleMode==="upload"?"Yüklenen jingle":"Jingle yok")+" · MP3 + WAV";const panel=document.querySelector("[data-radio-panel-duration]");if(panel)panel.textContent=duration+" sn";updateBudget(root)}

  function brief(root){const get=name=>String(q(root,'[data-radio-ad-input="'+name+'"]')?.value||"").trim();return{productName:get("productName"),brandName:get("brandName"),description:get("description"),targetAudience:get("targetAudience"),cta:get("cta")}}
  function createCopy(root){const b=brief(root);if(!b.productName&&!b.description){window.toastSafe?.("Önce ürün adı ve kısa açıklamayı doldur.","warning");q(root,'[data-radio-ad-input="productName"]')?.focus();return}const brand=b.brandName||b.productName||"Markanız";const product=b.productName||"bu çözüm";const benefit=b.description||"ihtiyacınız olan çözümü hızlı ve kolay biçimde sunar";const cta=b.cta||"Şimdi keşfedin";let text="";if(state.duration===15)text=brand+" ile "+product+". "+benefit+". "+cta+".";else if(state.duration===30)text="Daha hızlı, daha etkili ve daha profesyonel bir deneyim için "+product+". "+benefit+". "+brand+", işinizi kolaylaştırmak için yanınızda. "+cta+".";else if(state.duration===45)text="Zamanınızı doğru kullanmak ve daha güçlü sonuçlar almak artık çok daha kolay. "+product+", "+benefit+". "+(b.targetAudience?b.targetAudience+" için tasarlanan bu deneyim,":"Bu deneyim,")+" ihtiyacınız olan adımları tek yerde bir araya getirir. "+brand+" ile fikrinizi harekete geçirin. "+cta+".";else text="Gün içinde daha hızlı ilerlemek, daha profesyonel sonuçlar almak ve işinizi kolaylaştırmak ister misiniz? "+product+", "+benefit+". "+(b.targetAudience?b.targetAudience+" için geliştirilen":"Herkes için geliştirilen")+" bu çözüm, karmaşık adımları sadeleştirir ve ihtiyacınız olan deneyimi tek yerde sunar. "+brand+" ile zaman kazanın, hedefinize odaklanın ve fikrinizi gerçeğe dönüştürün. "+cta+".";const copy=q(root,"[data-radio-ad-copy]");if(copy){copy.value=text;copy.dispatchEvent(new Event("input",{bubbles:true}));copy.focus()}window.toastSafe?.("AIVO reklam metni hazırlandı. Dilersen metni düzenleyebilirsin.","success")}

  function setModeVisibility(root){const musicAI=q(root,"[data-radio-ad-music-ai]");const musicUpload=q(root,"[data-radio-ad-music-upload]");if(musicAI)musicAI.hidden=state.musicMode!=="ai";if(musicUpload)musicUpload.hidden=state.musicMode!=="upload";const jAI=q(root,"[data-radio-ad-jingle-ai]");const jUpload=q(root,"[data-radio-ad-jingle-upload]");if(jAI)jAI.hidden=state.jingleMode!=="ai";if(jUpload)jUpload.hidden=state.jingleMode!=="upload";updateTimeline(root)}

  function bindRoot(root){if(!root||root.dataset.radioAdBound==="1")return;root.dataset.radioAdBound="1";qa(root,"[data-radio-ad-count]").forEach(function(){return null});qa(root,"textarea,input").forEach(el=>el.addEventListener("input",function(){const key=el.matches("[data-radio-ad-copy]")?"copy":el.dataset.radioAdInput;const counter=key&&q(root,'[data-radio-ad-count="'+key+'"]');if(counter)counter.textContent=String(el.value||"").length;if(el.matches("[data-radio-ad-copy]"))updateBudget(root)}));qa(root,"[data-radio-ad-choice-group]").forEach(group=>group.addEventListener("click",function(event){const btn=event.target.closest("button[data-value]");if(!btn)return;event.preventDefault();qa(group,"button[data-value]").forEach(b=>b.classList.toggle("is-active",b===btn));const key=group.dataset.radioAdChoiceGroup;const value=btn.dataset.value;if(key==="duration")state.duration=Number(value)||30;else state[key]=value;if(key==="musicMode"||key==="jingleMode")setModeVisibility(root);else updateTimeline(root)}));q(root,'[data-radio-ad-action="prepare-copy"]')?.addEventListener("click",()=>createCopy(root));setModeVisibility(root);updateTimeline(root)}

  function mountForEvent(event){const key=event&&event.detail&&event.detail.key;const root=event&&event.detail&&event.detail.root;if(key==="adfilm"||key==="radioad")ensureSelector(key,root);if(key==="radioad")bindRoot(root)}
  function refresh(){ensureCss();ensureNav();applyVideoNaming();registerPanel();const active=document.getElementById("moduleHost")?.getAttribute("data-active-module");const root=document.querySelector('[data-module-root][data-module="'+active+'"]');if((active==="adfilm"||active==="radioad")&&root)ensureSelector(active,root);if(active==="radioad")bindRoot(root)}

  ensureCss();registerPanel();if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",refresh,{once:true});else refresh();document.addEventListener("aivo:module-mounted",mountForEvent);document.addEventListener("aivo:language-changed",refresh);document.addEventListener("aivo:lang-changed",refresh);const observer=new MutationObserver(function(){ensureNav();applyVideoNaming()});const startObserver=function(){const left=document.getElementById("leftMenu");if(left)observer.observe(left,{childList:true,subtree:true})};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",startObserver,{once:true});else startObserver();
})();
